//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administrador_Tarjetas.ObjetosDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUENTA
    {
        public decimal ID_CUENTA { get; set; }
        public string NUMERO_CUENTA { get; set; }
        public Nullable<decimal> ID_TIPO_CUENTA { get; set; }
        public Nullable<decimal> ID_CLIENTE { get; set; }
        public Nullable<decimal> SALDO_REAL { get; set; }
        public Nullable<decimal> PAGO_MINIMO { get; set; }
        public Nullable<decimal> SALDO_ULTIMO_PAGO_MINIMO { get; set; }
        public Nullable<decimal> INTERESES_MORATORIOS { get; set; }
        public Nullable<decimal> SALDO_PAGO_CONTADO { get; set; }
        public Nullable<decimal> SALDO_CORTE { get; set; }
    }
}
