//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administrador_Tarjetas.ObjetosDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CARGO_AUTOMATICO> CARGO_AUTOMATICO { get; set; }
        public virtual DbSet<CLIENTE> CLIENTE { get; set; }
        public virtual DbSet<CUENTA> CUENTA { get; set; }
        public virtual DbSet<MARCA_TARJETA> MARCA_TARJETA { get; set; }
        public virtual DbSet<PAGO> PAGO { get; set; }
        public virtual DbSet<TARJETA> TARJETA { get; set; }
        public virtual DbSet<TIPO_CARGO> TIPO_CARGO { get; set; }
        public virtual DbSet<TIPO_CLIENTE> TIPO_CLIENTE { get; set; }
        public virtual DbSet<TIPO_CUENTA> TIPO_CUENTA { get; set; }
        public virtual DbSet<TIPO_TRANSACCION> TIPO_TRANSACCION { get; set; }
        public virtual DbSet<TRANSACCION> TRANSACCION { get; set; }
    
        public virtual int ACTUALIZAR_CARGO_AUTOMATICO(Nullable<decimal> iD_CARGOP, Nullable<decimal> mONTOP, string nUMERO_TARJETAP, Nullable<decimal> fECHA_APLICACIONP, Nullable<decimal> iD_TIPO_CARGOP)
        {
            var iD_CARGOPParameter = iD_CARGOP.HasValue ?
                new ObjectParameter("ID_CARGOP", iD_CARGOP) :
                new ObjectParameter("ID_CARGOP", typeof(decimal));
    
            var mONTOPParameter = mONTOP.HasValue ?
                new ObjectParameter("MONTOP", mONTOP) :
                new ObjectParameter("MONTOP", typeof(decimal));
    
            var nUMERO_TARJETAPParameter = nUMERO_TARJETAP != null ?
                new ObjectParameter("NUMERO_TARJETAP", nUMERO_TARJETAP) :
                new ObjectParameter("NUMERO_TARJETAP", typeof(string));
    
            var fECHA_APLICACIONPParameter = fECHA_APLICACIONP.HasValue ?
                new ObjectParameter("FECHA_APLICACIONP", fECHA_APLICACIONP) :
                new ObjectParameter("FECHA_APLICACIONP", typeof(decimal));
    
            var iD_TIPO_CARGOPParameter = iD_TIPO_CARGOP.HasValue ?
                new ObjectParameter("ID_TIPO_CARGOP", iD_TIPO_CARGOP) :
                new ObjectParameter("ID_TIPO_CARGOP", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ACTUALIZAR_CARGO_AUTOMATICO", iD_CARGOPParameter, mONTOPParameter, nUMERO_TARJETAPParameter, fECHA_APLICACIONPParameter, iD_TIPO_CARGOPParameter);
        }
    
        public virtual int ACTUALIZAR_CLIENTE(string iD_CLIENTE_P, string nOMBRE_P, string pRIMER_APELLIDO_P, string sEGUNDO_APELLIDO_P, string cEDULA_P, Nullable<decimal> iD_TIPO_CLIENTE, Nullable<decimal> sALARIO_P)
        {
            var iD_CLIENTE_PParameter = iD_CLIENTE_P != null ?
                new ObjectParameter("ID_CLIENTE_P", iD_CLIENTE_P) :
                new ObjectParameter("ID_CLIENTE_P", typeof(string));
    
            var nOMBRE_PParameter = nOMBRE_P != null ?
                new ObjectParameter("NOMBRE_P", nOMBRE_P) :
                new ObjectParameter("NOMBRE_P", typeof(string));
    
            var pRIMER_APELLIDO_PParameter = pRIMER_APELLIDO_P != null ?
                new ObjectParameter("PRIMER_APELLIDO_P", pRIMER_APELLIDO_P) :
                new ObjectParameter("PRIMER_APELLIDO_P", typeof(string));
    
            var sEGUNDO_APELLIDO_PParameter = sEGUNDO_APELLIDO_P != null ?
                new ObjectParameter("SEGUNDO_APELLIDO_P", sEGUNDO_APELLIDO_P) :
                new ObjectParameter("SEGUNDO_APELLIDO_P", typeof(string));
    
            var cEDULA_PParameter = cEDULA_P != null ?
                new ObjectParameter("CEDULA_P", cEDULA_P) :
                new ObjectParameter("CEDULA_P", typeof(string));
    
            var iD_TIPO_CLIENTEParameter = iD_TIPO_CLIENTE.HasValue ?
                new ObjectParameter("ID_TIPO_CLIENTE", iD_TIPO_CLIENTE) :
                new ObjectParameter("ID_TIPO_CLIENTE", typeof(decimal));
    
            var sALARIO_PParameter = sALARIO_P.HasValue ?
                new ObjectParameter("SALARIO_P", sALARIO_P) :
                new ObjectParameter("SALARIO_P", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ACTUALIZAR_CLIENTE", iD_CLIENTE_PParameter, nOMBRE_PParameter, pRIMER_APELLIDO_PParameter, sEGUNDO_APELLIDO_PParameter, cEDULA_PParameter, iD_TIPO_CLIENTEParameter, sALARIO_PParameter);
        }
    
        public virtual int ACTUALIZAR_MARCA_TARJETA(Nullable<decimal> iD_MARCA_TARJETAP, string mARCAP)
        {
            var iD_MARCA_TARJETAPParameter = iD_MARCA_TARJETAP.HasValue ?
                new ObjectParameter("ID_MARCA_TARJETAP", iD_MARCA_TARJETAP) :
                new ObjectParameter("ID_MARCA_TARJETAP", typeof(decimal));
    
            var mARCAPParameter = mARCAP != null ?
                new ObjectParameter("MARCAP", mARCAP) :
                new ObjectParameter("MARCAP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ACTUALIZAR_MARCA_TARJETA", iD_MARCA_TARJETAPParameter, mARCAPParameter);
        }
    
        public virtual int ACTUALIZAR_PAGO(Nullable<decimal> iD_PAGOP, string nUMERO_CUENTAP, Nullable<decimal> mONTO_PAGOP, Nullable<System.DateTime> fECHAP)
        {
            var iD_PAGOPParameter = iD_PAGOP.HasValue ?
                new ObjectParameter("ID_PAGOP", iD_PAGOP) :
                new ObjectParameter("ID_PAGOP", typeof(decimal));
    
            var nUMERO_CUENTAPParameter = nUMERO_CUENTAP != null ?
                new ObjectParameter("NUMERO_CUENTAP", nUMERO_CUENTAP) :
                new ObjectParameter("NUMERO_CUENTAP", typeof(string));
    
            var mONTO_PAGOPParameter = mONTO_PAGOP.HasValue ?
                new ObjectParameter("MONTO_PAGOP", mONTO_PAGOP) :
                new ObjectParameter("MONTO_PAGOP", typeof(decimal));
    
            var fECHAPParameter = fECHAP.HasValue ?
                new ObjectParameter("FECHAP", fECHAP) :
                new ObjectParameter("FECHAP", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ACTUALIZAR_PAGO", iD_PAGOPParameter, nUMERO_CUENTAPParameter, mONTO_PAGOPParameter, fECHAPParameter);
        }
    
        public virtual int ACTUALIZAR_TARJETA(Nullable<decimal> iD_TARJETAP, string nUMERO_TARJETAP, Nullable<decimal> iD_CUENTAP, Nullable<decimal> iD_MARCA_TARJETAP, string cODIGO_SEGURIDADP, Nullable<decimal> lIMITEP)
        {
            var iD_TARJETAPParameter = iD_TARJETAP.HasValue ?
                new ObjectParameter("ID_TARJETAP", iD_TARJETAP) :
                new ObjectParameter("ID_TARJETAP", typeof(decimal));
    
            var nUMERO_TARJETAPParameter = nUMERO_TARJETAP != null ?
                new ObjectParameter("NUMERO_TARJETAP", nUMERO_TARJETAP) :
                new ObjectParameter("NUMERO_TARJETAP", typeof(string));
    
            var iD_CUENTAPParameter = iD_CUENTAP.HasValue ?
                new ObjectParameter("ID_CUENTAP", iD_CUENTAP) :
                new ObjectParameter("ID_CUENTAP", typeof(decimal));
    
            var iD_MARCA_TARJETAPParameter = iD_MARCA_TARJETAP.HasValue ?
                new ObjectParameter("ID_MARCA_TARJETAP", iD_MARCA_TARJETAP) :
                new ObjectParameter("ID_MARCA_TARJETAP", typeof(decimal));
    
            var cODIGO_SEGURIDADPParameter = cODIGO_SEGURIDADP != null ?
                new ObjectParameter("CODIGO_SEGURIDADP", cODIGO_SEGURIDADP) :
                new ObjectParameter("CODIGO_SEGURIDADP", typeof(string));
    
            var lIMITEPParameter = lIMITEP.HasValue ?
                new ObjectParameter("LIMITEP", lIMITEP) :
                new ObjectParameter("LIMITEP", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ACTUALIZAR_TARJETA", iD_TARJETAPParameter, nUMERO_TARJETAPParameter, iD_CUENTAPParameter, iD_MARCA_TARJETAPParameter, cODIGO_SEGURIDADPParameter, lIMITEPParameter);
        }
    
        public virtual int ACTUALIZAR_TIPO_CARGO(Nullable<decimal> iD_TIPO_CARGOP, string tIPO_CARGOP)
        {
            var iD_TIPO_CARGOPParameter = iD_TIPO_CARGOP.HasValue ?
                new ObjectParameter("ID_TIPO_CARGOP", iD_TIPO_CARGOP) :
                new ObjectParameter("ID_TIPO_CARGOP", typeof(decimal));
    
            var tIPO_CARGOPParameter = tIPO_CARGOP != null ?
                new ObjectParameter("TIPO_CARGOP", tIPO_CARGOP) :
                new ObjectParameter("TIPO_CARGOP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ACTUALIZAR_TIPO_CARGO", iD_TIPO_CARGOPParameter, tIPO_CARGOPParameter);
        }
    
        public virtual int ACTUALIZAR_TIPOCLIENTE(Nullable<decimal> iD_TIPO_CLIENTEP, string tIPO_CLIENTEP)
        {
            var iD_TIPO_CLIENTEPParameter = iD_TIPO_CLIENTEP.HasValue ?
                new ObjectParameter("ID_TIPO_CLIENTEP", iD_TIPO_CLIENTEP) :
                new ObjectParameter("ID_TIPO_CLIENTEP", typeof(decimal));
    
            var tIPO_CLIENTEPParameter = tIPO_CLIENTEP != null ?
                new ObjectParameter("TIPO_CLIENTEP", tIPO_CLIENTEP) :
                new ObjectParameter("TIPO_CLIENTEP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ACTUALIZAR_TIPOCLIENTE", iD_TIPO_CLIENTEPParameter, tIPO_CLIENTEPParameter);
        }
    
        public virtual int ACTUALIZAR_TIPOCUENTA(Nullable<decimal> iD_TIPO_CUENTAP, string tIPO_CUENTAP, Nullable<decimal> tASA_INTERES_DIARIAP, Nullable<decimal> tASA_MORAP, Nullable<decimal> dIAS_PAGO_MINIMOP, Nullable<decimal> dIAS_PAGO_CONTADOP, Nullable<decimal> dIA_CORTEP, Nullable<decimal> cOMISION_RETIROP, Nullable<decimal> cOMISION_ADMINISTRACIONP, Nullable<decimal> mESES_FINANCIACIONP)
        {
            var iD_TIPO_CUENTAPParameter = iD_TIPO_CUENTAP.HasValue ?
                new ObjectParameter("ID_TIPO_CUENTAP", iD_TIPO_CUENTAP) :
                new ObjectParameter("ID_TIPO_CUENTAP", typeof(decimal));
    
            var tIPO_CUENTAPParameter = tIPO_CUENTAP != null ?
                new ObjectParameter("TIPO_CUENTAP", tIPO_CUENTAP) :
                new ObjectParameter("TIPO_CUENTAP", typeof(string));
    
            var tASA_INTERES_DIARIAPParameter = tASA_INTERES_DIARIAP.HasValue ?
                new ObjectParameter("TASA_INTERES_DIARIAP", tASA_INTERES_DIARIAP) :
                new ObjectParameter("TASA_INTERES_DIARIAP", typeof(decimal));
    
            var tASA_MORAPParameter = tASA_MORAP.HasValue ?
                new ObjectParameter("TASA_MORAP", tASA_MORAP) :
                new ObjectParameter("TASA_MORAP", typeof(decimal));
    
            var dIAS_PAGO_MINIMOPParameter = dIAS_PAGO_MINIMOP.HasValue ?
                new ObjectParameter("DIAS_PAGO_MINIMOP", dIAS_PAGO_MINIMOP) :
                new ObjectParameter("DIAS_PAGO_MINIMOP", typeof(decimal));
    
            var dIAS_PAGO_CONTADOPParameter = dIAS_PAGO_CONTADOP.HasValue ?
                new ObjectParameter("DIAS_PAGO_CONTADOP", dIAS_PAGO_CONTADOP) :
                new ObjectParameter("DIAS_PAGO_CONTADOP", typeof(decimal));
    
            var dIA_CORTEPParameter = dIA_CORTEP.HasValue ?
                new ObjectParameter("DIA_CORTEP", dIA_CORTEP) :
                new ObjectParameter("DIA_CORTEP", typeof(decimal));
    
            var cOMISION_RETIROPParameter = cOMISION_RETIROP.HasValue ?
                new ObjectParameter("COMISION_RETIROP", cOMISION_RETIROP) :
                new ObjectParameter("COMISION_RETIROP", typeof(decimal));
    
            var cOMISION_ADMINISTRACIONPParameter = cOMISION_ADMINISTRACIONP.HasValue ?
                new ObjectParameter("COMISION_ADMINISTRACIONP", cOMISION_ADMINISTRACIONP) :
                new ObjectParameter("COMISION_ADMINISTRACIONP", typeof(decimal));
    
            var mESES_FINANCIACIONPParameter = mESES_FINANCIACIONP.HasValue ?
                new ObjectParameter("MESES_FINANCIACIONP", mESES_FINANCIACIONP) :
                new ObjectParameter("MESES_FINANCIACIONP", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ACTUALIZAR_TIPOCUENTA", iD_TIPO_CUENTAPParameter, tIPO_CUENTAPParameter, tASA_INTERES_DIARIAPParameter, tASA_MORAPParameter, dIAS_PAGO_MINIMOPParameter, dIAS_PAGO_CONTADOPParameter, dIA_CORTEPParameter, cOMISION_RETIROPParameter, cOMISION_ADMINISTRACIONPParameter, mESES_FINANCIACIONPParameter);
        }
    
        public virtual int ACTUALIZAR_TIPO_TRANSACCION(Nullable<decimal> iD_TIPO_TRANSACCIONP, string tIPO_TRANSACCIONP)
        {
            var iD_TIPO_TRANSACCIONPParameter = iD_TIPO_TRANSACCIONP.HasValue ?
                new ObjectParameter("ID_TIPO_TRANSACCIONP", iD_TIPO_TRANSACCIONP) :
                new ObjectParameter("ID_TIPO_TRANSACCIONP", typeof(decimal));
    
            var tIPO_TRANSACCIONPParameter = tIPO_TRANSACCIONP != null ?
                new ObjectParameter("TIPO_TRANSACCIONP", tIPO_TRANSACCIONP) :
                new ObjectParameter("TIPO_TRANSACCIONP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ACTUALIZAR_TIPO_TRANSACCION", iD_TIPO_TRANSACCIONPParameter, tIPO_TRANSACCIONPParameter);
        }
    
        public virtual int ACTUALIZAR_TRANSACCION(Nullable<decimal> iD_TRANSACCIONP, Nullable<decimal> iD_TIPO_TRANSACCIONP, Nullable<decimal> mONTOP, string nUMERO_CUENTAP, string cUENTA_REFERENCIAP, Nullable<System.DateTime> fECHAP)
        {
            var iD_TRANSACCIONPParameter = iD_TRANSACCIONP.HasValue ?
                new ObjectParameter("ID_TRANSACCIONP", iD_TRANSACCIONP) :
                new ObjectParameter("ID_TRANSACCIONP", typeof(decimal));
    
            var iD_TIPO_TRANSACCIONPParameter = iD_TIPO_TRANSACCIONP.HasValue ?
                new ObjectParameter("ID_TIPO_TRANSACCIONP", iD_TIPO_TRANSACCIONP) :
                new ObjectParameter("ID_TIPO_TRANSACCIONP", typeof(decimal));
    
            var mONTOPParameter = mONTOP.HasValue ?
                new ObjectParameter("MONTOP", mONTOP) :
                new ObjectParameter("MONTOP", typeof(decimal));
    
            var nUMERO_CUENTAPParameter = nUMERO_CUENTAP != null ?
                new ObjectParameter("NUMERO_CUENTAP", nUMERO_CUENTAP) :
                new ObjectParameter("NUMERO_CUENTAP", typeof(string));
    
            var cUENTA_REFERENCIAPParameter = cUENTA_REFERENCIAP != null ?
                new ObjectParameter("CUENTA_REFERENCIAP", cUENTA_REFERENCIAP) :
                new ObjectParameter("CUENTA_REFERENCIAP", typeof(string));
    
            var fECHAPParameter = fECHAP.HasValue ?
                new ObjectParameter("FECHAP", fECHAP) :
                new ObjectParameter("FECHAP", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ACTUALIZAR_TRANSACCION", iD_TRANSACCIONPParameter, iD_TIPO_TRANSACCIONPParameter, mONTOPParameter, nUMERO_CUENTAPParameter, cUENTA_REFERENCIAPParameter, fECHAPParameter);
        }
    
        public virtual int ELIMINAR_CARGO_AUTOMATICO(Nullable<decimal> iD_CARGOP)
        {
            var iD_CARGOPParameter = iD_CARGOP.HasValue ?
                new ObjectParameter("ID_CARGOP", iD_CARGOP) :
                new ObjectParameter("ID_CARGOP", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ELIMINAR_CARGO_AUTOMATICO", iD_CARGOPParameter);
        }
    
        public virtual int ELIMINAR_CLIENTE(string iD_CLIENTE_P)
        {
            var iD_CLIENTE_PParameter = iD_CLIENTE_P != null ?
                new ObjectParameter("ID_CLIENTE_P", iD_CLIENTE_P) :
                new ObjectParameter("ID_CLIENTE_P", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ELIMINAR_CLIENTE", iD_CLIENTE_PParameter);
        }
    
        public virtual int ELIMINAR_CUENTA(Nullable<decimal> iD_CUENTAP)
        {
            var iD_CUENTAPParameter = iD_CUENTAP.HasValue ?
                new ObjectParameter("ID_CUENTAP", iD_CUENTAP) :
                new ObjectParameter("ID_CUENTAP", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ELIMINAR_CUENTA", iD_CUENTAPParameter);
        }
    
        public virtual int ELIMINAR_MARCA_TARJETA(Nullable<decimal> iD_MARCA_TARJETAP)
        {
            var iD_MARCA_TARJETAPParameter = iD_MARCA_TARJETAP.HasValue ?
                new ObjectParameter("ID_MARCA_TARJETAP", iD_MARCA_TARJETAP) :
                new ObjectParameter("ID_MARCA_TARJETAP", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ELIMINAR_MARCA_TARJETA", iD_MARCA_TARJETAPParameter);
        }
    
        public virtual int ELIMINAR_PAGO(Nullable<decimal> iD_PAGOP)
        {
            var iD_PAGOPParameter = iD_PAGOP.HasValue ?
                new ObjectParameter("ID_PAGOP", iD_PAGOP) :
                new ObjectParameter("ID_PAGOP", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ELIMINAR_PAGO", iD_PAGOPParameter);
        }
    
        public virtual int ELIMINAR_TARJETA(Nullable<decimal> iD_TARJETAP)
        {
            var iD_TARJETAPParameter = iD_TARJETAP.HasValue ?
                new ObjectParameter("ID_TARJETAP", iD_TARJETAP) :
                new ObjectParameter("ID_TARJETAP", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ELIMINAR_TARJETA", iD_TARJETAPParameter);
        }
    
        public virtual int ELIMINAR_TIPO_CARGO(Nullable<decimal> iD_TIPO_CARGOP)
        {
            var iD_TIPO_CARGOPParameter = iD_TIPO_CARGOP.HasValue ?
                new ObjectParameter("ID_TIPO_CARGOP", iD_TIPO_CARGOP) :
                new ObjectParameter("ID_TIPO_CARGOP", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ELIMINAR_TIPO_CARGO", iD_TIPO_CARGOPParameter);
        }
    
        public virtual int ELIMINAR_TIPOCLIENTE(string iD_TIPOCLIENTE_P)
        {
            var iD_TIPOCLIENTE_PParameter = iD_TIPOCLIENTE_P != null ?
                new ObjectParameter("ID_TIPOCLIENTE_P", iD_TIPOCLIENTE_P) :
                new ObjectParameter("ID_TIPOCLIENTE_P", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ELIMINAR_TIPOCLIENTE", iD_TIPOCLIENTE_PParameter);
        }
    
        public virtual int ELIMINAR_TIPOCUENTA(Nullable<decimal> iD_TIPOCUENTA_P)
        {
            var iD_TIPOCUENTA_PParameter = iD_TIPOCUENTA_P.HasValue ?
                new ObjectParameter("ID_TIPOCUENTA_P", iD_TIPOCUENTA_P) :
                new ObjectParameter("ID_TIPOCUENTA_P", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ELIMINAR_TIPOCUENTA", iD_TIPOCUENTA_PParameter);
        }
    
        public virtual int ELIMINAR_TIPO_TRANSACCION(Nullable<decimal> iD_TIPO_TRANSACCIONP)
        {
            var iD_TIPO_TRANSACCIONPParameter = iD_TIPO_TRANSACCIONP.HasValue ?
                new ObjectParameter("ID_TIPO_TRANSACCIONP", iD_TIPO_TRANSACCIONP) :
                new ObjectParameter("ID_TIPO_TRANSACCIONP", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ELIMINAR_TIPO_TRANSACCION", iD_TIPO_TRANSACCIONPParameter);
        }
    
        public virtual int ELIMINAR_TRANSACCION(Nullable<decimal> iD_TRANSACCIONP)
        {
            var iD_TRANSACCIONPParameter = iD_TRANSACCIONP.HasValue ?
                new ObjectParameter("ID_TRANSACCIONP", iD_TRANSACCIONP) :
                new ObjectParameter("ID_TRANSACCIONP", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ELIMINAR_TRANSACCION", iD_TRANSACCIONPParameter);
        }
    
        public virtual int INSERTAR_CARGO_AUTOMATICO(Nullable<decimal> iD_CARGOP, Nullable<decimal> mONTOP, string nUMERO_TARJETAP, Nullable<decimal> fECHA_APLICACIONP, Nullable<decimal> iD_TIPO_CARGOP)
        {
            var iD_CARGOPParameter = iD_CARGOP.HasValue ?
                new ObjectParameter("ID_CARGOP", iD_CARGOP) :
                new ObjectParameter("ID_CARGOP", typeof(decimal));
    
            var mONTOPParameter = mONTOP.HasValue ?
                new ObjectParameter("MONTOP", mONTOP) :
                new ObjectParameter("MONTOP", typeof(decimal));
    
            var nUMERO_TARJETAPParameter = nUMERO_TARJETAP != null ?
                new ObjectParameter("NUMERO_TARJETAP", nUMERO_TARJETAP) :
                new ObjectParameter("NUMERO_TARJETAP", typeof(string));
    
            var fECHA_APLICACIONPParameter = fECHA_APLICACIONP.HasValue ?
                new ObjectParameter("FECHA_APLICACIONP", fECHA_APLICACIONP) :
                new ObjectParameter("FECHA_APLICACIONP", typeof(decimal));
    
            var iD_TIPO_CARGOPParameter = iD_TIPO_CARGOP.HasValue ?
                new ObjectParameter("ID_TIPO_CARGOP", iD_TIPO_CARGOP) :
                new ObjectParameter("ID_TIPO_CARGOP", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTAR_CARGO_AUTOMATICO", iD_CARGOPParameter, mONTOPParameter, nUMERO_TARJETAPParameter, fECHA_APLICACIONPParameter, iD_TIPO_CARGOPParameter);
        }
    
        public virtual int INSERTAR_CLIENTE(string iD_CLIENTE_P, string nOMBRE_P, string pRIMER_APELLIDO_P, string sEGUNDO_APELLIDO_P, string cEDULA_P, Nullable<decimal> iD_TIPO_CLIENTE, Nullable<decimal> sALARIO_P)
        {
            var iD_CLIENTE_PParameter = iD_CLIENTE_P != null ?
                new ObjectParameter("ID_CLIENTE_P", iD_CLIENTE_P) :
                new ObjectParameter("ID_CLIENTE_P", typeof(string));
    
            var nOMBRE_PParameter = nOMBRE_P != null ?
                new ObjectParameter("NOMBRE_P", nOMBRE_P) :
                new ObjectParameter("NOMBRE_P", typeof(string));
    
            var pRIMER_APELLIDO_PParameter = pRIMER_APELLIDO_P != null ?
                new ObjectParameter("PRIMER_APELLIDO_P", pRIMER_APELLIDO_P) :
                new ObjectParameter("PRIMER_APELLIDO_P", typeof(string));
    
            var sEGUNDO_APELLIDO_PParameter = sEGUNDO_APELLIDO_P != null ?
                new ObjectParameter("SEGUNDO_APELLIDO_P", sEGUNDO_APELLIDO_P) :
                new ObjectParameter("SEGUNDO_APELLIDO_P", typeof(string));
    
            var cEDULA_PParameter = cEDULA_P != null ?
                new ObjectParameter("CEDULA_P", cEDULA_P) :
                new ObjectParameter("CEDULA_P", typeof(string));
    
            var iD_TIPO_CLIENTEParameter = iD_TIPO_CLIENTE.HasValue ?
                new ObjectParameter("ID_TIPO_CLIENTE", iD_TIPO_CLIENTE) :
                new ObjectParameter("ID_TIPO_CLIENTE", typeof(decimal));
    
            var sALARIO_PParameter = sALARIO_P.HasValue ?
                new ObjectParameter("SALARIO_P", sALARIO_P) :
                new ObjectParameter("SALARIO_P", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTAR_CLIENTE", iD_CLIENTE_PParameter, nOMBRE_PParameter, pRIMER_APELLIDO_PParameter, sEGUNDO_APELLIDO_PParameter, cEDULA_PParameter, iD_TIPO_CLIENTEParameter, sALARIO_PParameter);
        }
    
        public virtual int INSERTAR_MARCA_TARJETA(Nullable<decimal> iD_MARCA_TARJETAP, string mARCAP)
        {
            var iD_MARCA_TARJETAPParameter = iD_MARCA_TARJETAP.HasValue ?
                new ObjectParameter("ID_MARCA_TARJETAP", iD_MARCA_TARJETAP) :
                new ObjectParameter("ID_MARCA_TARJETAP", typeof(decimal));
    
            var mARCAPParameter = mARCAP != null ?
                new ObjectParameter("MARCAP", mARCAP) :
                new ObjectParameter("MARCAP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTAR_MARCA_TARJETA", iD_MARCA_TARJETAPParameter, mARCAPParameter);
        }
    
        public virtual int INSERTAR_PAGO(Nullable<decimal> iD_PAGOP, string nUMERO_CUENTAP, Nullable<decimal> mONTO_PAGOP, Nullable<System.DateTime> fECHAP)
        {
            var iD_PAGOPParameter = iD_PAGOP.HasValue ?
                new ObjectParameter("ID_PAGOP", iD_PAGOP) :
                new ObjectParameter("ID_PAGOP", typeof(decimal));
    
            var nUMERO_CUENTAPParameter = nUMERO_CUENTAP != null ?
                new ObjectParameter("NUMERO_CUENTAP", nUMERO_CUENTAP) :
                new ObjectParameter("NUMERO_CUENTAP", typeof(string));
    
            var mONTO_PAGOPParameter = mONTO_PAGOP.HasValue ?
                new ObjectParameter("MONTO_PAGOP", mONTO_PAGOP) :
                new ObjectParameter("MONTO_PAGOP", typeof(decimal));
    
            var fECHAPParameter = fECHAP.HasValue ?
                new ObjectParameter("FECHAP", fECHAP) :
                new ObjectParameter("FECHAP", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTAR_PAGO", iD_PAGOPParameter, nUMERO_CUENTAPParameter, mONTO_PAGOPParameter, fECHAPParameter);
        }
    
        public virtual int INSERTAR_TARJETA(Nullable<decimal> iD_TARJETAP, string nUMERO_TARJETAP, Nullable<decimal> iD_CUENTAP, Nullable<decimal> iD_MARCA_TARJETAP, string cODIGO_SEGURIDADP, Nullable<decimal> lIMITEP)
        {
            var iD_TARJETAPParameter = iD_TARJETAP.HasValue ?
                new ObjectParameter("ID_TARJETAP", iD_TARJETAP) :
                new ObjectParameter("ID_TARJETAP", typeof(decimal));
    
            var nUMERO_TARJETAPParameter = nUMERO_TARJETAP != null ?
                new ObjectParameter("NUMERO_TARJETAP", nUMERO_TARJETAP) :
                new ObjectParameter("NUMERO_TARJETAP", typeof(string));
    
            var iD_CUENTAPParameter = iD_CUENTAP.HasValue ?
                new ObjectParameter("ID_CUENTAP", iD_CUENTAP) :
                new ObjectParameter("ID_CUENTAP", typeof(decimal));
    
            var iD_MARCA_TARJETAPParameter = iD_MARCA_TARJETAP.HasValue ?
                new ObjectParameter("ID_MARCA_TARJETAP", iD_MARCA_TARJETAP) :
                new ObjectParameter("ID_MARCA_TARJETAP", typeof(decimal));
    
            var cODIGO_SEGURIDADPParameter = cODIGO_SEGURIDADP != null ?
                new ObjectParameter("CODIGO_SEGURIDADP", cODIGO_SEGURIDADP) :
                new ObjectParameter("CODIGO_SEGURIDADP", typeof(string));
    
            var lIMITEPParameter = lIMITEP.HasValue ?
                new ObjectParameter("LIMITEP", lIMITEP) :
                new ObjectParameter("LIMITEP", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTAR_TARJETA", iD_TARJETAPParameter, nUMERO_TARJETAPParameter, iD_CUENTAPParameter, iD_MARCA_TARJETAPParameter, cODIGO_SEGURIDADPParameter, lIMITEPParameter);
        }
    
        public virtual int INSERTAR_TIPO_CARGO(Nullable<decimal> iD_TIPO_CARGOP, string tIPO_CARGOP)
        {
            var iD_TIPO_CARGOPParameter = iD_TIPO_CARGOP.HasValue ?
                new ObjectParameter("ID_TIPO_CARGOP", iD_TIPO_CARGOP) :
                new ObjectParameter("ID_TIPO_CARGOP", typeof(decimal));
    
            var tIPO_CARGOPParameter = tIPO_CARGOP != null ?
                new ObjectParameter("TIPO_CARGOP", tIPO_CARGOP) :
                new ObjectParameter("TIPO_CARGOP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTAR_TIPO_CARGO", iD_TIPO_CARGOPParameter, tIPO_CARGOPParameter);
        }
    
        public virtual int INSERTAR_TIPOCLIENTE(Nullable<decimal> iD_TIPO_CLIENTEP, string tIPO_CLIENTEP)
        {
            var iD_TIPO_CLIENTEPParameter = iD_TIPO_CLIENTEP.HasValue ?
                new ObjectParameter("ID_TIPO_CLIENTEP", iD_TIPO_CLIENTEP) :
                new ObjectParameter("ID_TIPO_CLIENTEP", typeof(decimal));
    
            var tIPO_CLIENTEPParameter = tIPO_CLIENTEP != null ?
                new ObjectParameter("TIPO_CLIENTEP", tIPO_CLIENTEP) :
                new ObjectParameter("TIPO_CLIENTEP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTAR_TIPOCLIENTE", iD_TIPO_CLIENTEPParameter, tIPO_CLIENTEPParameter);
        }
    
        public virtual int INSERTAR_TIPOCUENTA(Nullable<decimal> iD_TIPO_CUENTAP, string tIPO_CUENTAP, Nullable<decimal> tASA_INTERES_DIARIAP, Nullable<decimal> tASA_MORAP, Nullable<decimal> dIAS_PAGO_MINIMOP, Nullable<decimal> dIAS_PAGO_CONTADOP, Nullable<decimal> dIA_CORTEP, Nullable<decimal> cOMISION_RETIROP, Nullable<decimal> cOMISION_ADMINISTRACIONP, Nullable<decimal> mESES_FINANCIACION)
        {
            var iD_TIPO_CUENTAPParameter = iD_TIPO_CUENTAP.HasValue ?
                new ObjectParameter("ID_TIPO_CUENTAP", iD_TIPO_CUENTAP) :
                new ObjectParameter("ID_TIPO_CUENTAP", typeof(decimal));
    
            var tIPO_CUENTAPParameter = tIPO_CUENTAP != null ?
                new ObjectParameter("TIPO_CUENTAP", tIPO_CUENTAP) :
                new ObjectParameter("TIPO_CUENTAP", typeof(string));
    
            var tASA_INTERES_DIARIAPParameter = tASA_INTERES_DIARIAP.HasValue ?
                new ObjectParameter("TASA_INTERES_DIARIAP", tASA_INTERES_DIARIAP) :
                new ObjectParameter("TASA_INTERES_DIARIAP", typeof(decimal));
    
            var tASA_MORAPParameter = tASA_MORAP.HasValue ?
                new ObjectParameter("TASA_MORAP", tASA_MORAP) :
                new ObjectParameter("TASA_MORAP", typeof(decimal));
    
            var dIAS_PAGO_MINIMOPParameter = dIAS_PAGO_MINIMOP.HasValue ?
                new ObjectParameter("DIAS_PAGO_MINIMOP", dIAS_PAGO_MINIMOP) :
                new ObjectParameter("DIAS_PAGO_MINIMOP", typeof(decimal));
    
            var dIAS_PAGO_CONTADOPParameter = dIAS_PAGO_CONTADOP.HasValue ?
                new ObjectParameter("DIAS_PAGO_CONTADOP", dIAS_PAGO_CONTADOP) :
                new ObjectParameter("DIAS_PAGO_CONTADOP", typeof(decimal));
    
            var dIA_CORTEPParameter = dIA_CORTEP.HasValue ?
                new ObjectParameter("DIA_CORTEP", dIA_CORTEP) :
                new ObjectParameter("DIA_CORTEP", typeof(decimal));
    
            var cOMISION_RETIROPParameter = cOMISION_RETIROP.HasValue ?
                new ObjectParameter("COMISION_RETIROP", cOMISION_RETIROP) :
                new ObjectParameter("COMISION_RETIROP", typeof(decimal));
    
            var cOMISION_ADMINISTRACIONPParameter = cOMISION_ADMINISTRACIONP.HasValue ?
                new ObjectParameter("COMISION_ADMINISTRACIONP", cOMISION_ADMINISTRACIONP) :
                new ObjectParameter("COMISION_ADMINISTRACIONP", typeof(decimal));
    
            var mESES_FINANCIACIONParameter = mESES_FINANCIACION.HasValue ?
                new ObjectParameter("MESES_FINANCIACION", mESES_FINANCIACION) :
                new ObjectParameter("MESES_FINANCIACION", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTAR_TIPOCUENTA", iD_TIPO_CUENTAPParameter, tIPO_CUENTAPParameter, tASA_INTERES_DIARIAPParameter, tASA_MORAPParameter, dIAS_PAGO_MINIMOPParameter, dIAS_PAGO_CONTADOPParameter, dIA_CORTEPParameter, cOMISION_RETIROPParameter, cOMISION_ADMINISTRACIONPParameter, mESES_FINANCIACIONParameter);
        }
    
        public virtual int INSERTAR_TIPO_TRANSACCION(Nullable<decimal> iD_TIPO_TRANSACCIONP, string tIPO_TRANSACCIONP)
        {
            var iD_TIPO_TRANSACCIONPParameter = iD_TIPO_TRANSACCIONP.HasValue ?
                new ObjectParameter("ID_TIPO_TRANSACCIONP", iD_TIPO_TRANSACCIONP) :
                new ObjectParameter("ID_TIPO_TRANSACCIONP", typeof(decimal));
    
            var tIPO_TRANSACCIONPParameter = tIPO_TRANSACCIONP != null ?
                new ObjectParameter("TIPO_TRANSACCIONP", tIPO_TRANSACCIONP) :
                new ObjectParameter("TIPO_TRANSACCIONP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTAR_TIPO_TRANSACCION", iD_TIPO_TRANSACCIONPParameter, tIPO_TRANSACCIONPParameter);
        }
    
        public virtual int INSERTAR_TRANSACCION(Nullable<decimal> iD_TRANSACCIONP, Nullable<decimal> iD_TIPO_TRANSACCIONP, Nullable<decimal> mONTOP, string nUMERO_CUENTAP, string cUENTA_REFERENCIAP, Nullable<System.DateTime> fECHAP)
        {
            var iD_TRANSACCIONPParameter = iD_TRANSACCIONP.HasValue ?
                new ObjectParameter("ID_TRANSACCIONP", iD_TRANSACCIONP) :
                new ObjectParameter("ID_TRANSACCIONP", typeof(decimal));
    
            var iD_TIPO_TRANSACCIONPParameter = iD_TIPO_TRANSACCIONP.HasValue ?
                new ObjectParameter("ID_TIPO_TRANSACCIONP", iD_TIPO_TRANSACCIONP) :
                new ObjectParameter("ID_TIPO_TRANSACCIONP", typeof(decimal));
    
            var mONTOPParameter = mONTOP.HasValue ?
                new ObjectParameter("MONTOP", mONTOP) :
                new ObjectParameter("MONTOP", typeof(decimal));
    
            var nUMERO_CUENTAPParameter = nUMERO_CUENTAP != null ?
                new ObjectParameter("NUMERO_CUENTAP", nUMERO_CUENTAP) :
                new ObjectParameter("NUMERO_CUENTAP", typeof(string));
    
            var cUENTA_REFERENCIAPParameter = cUENTA_REFERENCIAP != null ?
                new ObjectParameter("CUENTA_REFERENCIAP", cUENTA_REFERENCIAP) :
                new ObjectParameter("CUENTA_REFERENCIAP", typeof(string));
    
            var fECHAPParameter = fECHAP.HasValue ?
                new ObjectParameter("FECHAP", fECHAP) :
                new ObjectParameter("FECHAP", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTAR_TRANSACCION", iD_TRANSACCIONPParameter, iD_TIPO_TRANSACCIONPParameter, mONTOPParameter, nUMERO_CUENTAPParameter, cUENTA_REFERENCIAPParameter, fECHAPParameter);
        }
    
        public virtual int OBTENER_CARGO_AUTOMATICO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("OBTENER_CARGO_AUTOMATICO");
        }
    
        public virtual int OBTENER_CLIENTES()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("OBTENER_CLIENTES");
        }
    
        public virtual int OBTENER_CUENTA()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("OBTENER_CUENTA");
        }
    
        public virtual int OBTENER_MARCA_TARJETA()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("OBTENER_MARCA_TARJETA");
        }
    
        public virtual int OBTENER_PAGO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("OBTENER_PAGO");
        }
    
        public virtual int OBTENER_TARJETA()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("OBTENER_TARJETA");
        }
    
        public virtual int OBTENER_TIPO_CARGO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("OBTENER_TIPO_CARGO");
        }
    
        public virtual int OBTENER_TIPO_CLIENTES()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("OBTENER_TIPO_CLIENTES");
        }
    
        public virtual int OBTENER_TIPO_TRANSACCION()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("OBTENER_TIPO_TRANSACCION");
        }
    
        public virtual int OBTENER_TRANSACCION()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("OBTENER_TRANSACCION");
        }
    }
}
