//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administrador_Tarjetas.ObjetosDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGO
    {
        public decimal ID_PAGO { get; set; }
        public string NUMERO_CUENTA { get; set; }
        public Nullable<decimal> MONTO_PAGO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
    }
}
