//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administrador_Tarjetas.ObjetosDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_CLIENTE
    {
        public decimal ID_TIPO_CLIENTE { get; set; }
        public string TIPO_CLIENTE1 { get; set; }
    }
}
